set(CPACK_PACKAGE_NAME "TMD56Monitor")
set(CPACK_PACKAGE_VENDOR "TMD56 Monitor Project")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "TMD-56 Temperature Logger")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "TMD56 Temperature Logger")
set(CPACK_PACKAGE_FILE_NAME "TMD56Monitor")

if(WIN32)
    set(CPACK_GENERATOR "NSIS;ZIP")
    # x64 Program Files. Version comes from the CMake project() version.
    set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
    set(CPACK_NSIS_PACKAGE_NAME "TMD-56 Temperature Logger")
    set(CPACK_NSIS_DISPLAY_NAME "TMD-56 Temperature Logger")
    set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/resources/icons/tmd56-monitor.ico")
    set(CPACK_NSIS_MUI_UNIICON "${CMAKE_SOURCE_DIR}/resources/icons/tmd56-monitor.ico")
    set(CPACK_NSIS_INSTALLED_ICON_NAME "tmd56-monitor.exe")
    set(CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
    set(CPACK_NSIS_MODIFY_PATH OFF)
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
    set(CPACK_PACKAGE_EXECUTABLES "tmd56-monitor;TMD-56 Temperature Logger")
    set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "TMD56 Temperature Logger")
    # The uninstaller deletes only the Program Files tree created here.
    # CSV logs live in %LOCALAPPDATA%\\TMD56Monitor\\logs and are left in place.
else()
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_PACKAGE_NAME "tmd56-monitor")
    set(CPACK_DEBIAN_FILE_NAME "TMD56Monitor_${PROJECT_VERSION}_amd64.deb")
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
    set(CPACK_DEBIAN_PACKAGE_SECTION "science")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "TMD56 Monitor Project <tmd56-monitor@localhost>")
    set(CPACK_PACKAGE_CONTACT "TMD56 Monitor Project <tmd56-monitor@localhost>")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libgtk-4-1 (>= 4.10), libcairo2, libserialport0, libglib2.0-0t64 | libglib2.0-0")
    set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Dual-input temperature logger.\n Simulation and file replay. Not an official Amprobe product.")
    set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
endif()

include(CPack)
